package com.example.randomquestions;
import java.util.List;

public class Family_Friendly {
    public void AddQuestions(List<String> Questions){
        //Add Family Friendly Questions
        ///FAMILY FRIENDLY
	Questions.add("How often do you bathe?");
	Questions.add("Do you like potatoes?");
	Questions.add("Do you like peanut butter?");
        Questions.add("What's your zodiac sign (more importantly, when is your birthday)?");
        Questions.add("What is the best compliment you have ever received?");
        Questions.add("Given the choice of anyone in the world, whom would you want as a dinner guest?");
        Questions.add("Would you like to be famous? In what way?");
        Questions.add("Before making a telephone call, do you ever rehearse what you are going to say? Why or why not?");
        Questions.add("What would constitute a perfect day for you?");
        Questions.add("When did you last sing to yourself?");
        Questions.add("When did you last sing to someone else?");
        Questions.add("If you were able to live to the age of 90 and retain either the mind of a 30 year old or the body of a 30 year for the years from 30-90 what would you choose and why?");
        Questions.add("What is your relationship with cheese?");
        Questions.add("Give me an example of a pet peeve?");
        Questions.add("What is your favorite color?");
        Questions.add("What's your favorite food?");
        Questions.add("What is something that makes you lose track of time?");
        Questions.add("What are ten things you would bring to a desert island?");
        Questions.add("What is your favorite movie?");
        Questions.add("What movie do you basically have memorized?");
        Questions.add("When you fly do you prefer the window or aisle seat?");
        Questions.add("What's something you love but others hate?");
        Questions.add("What's your best animal impression?");
        Questions.add("Chocolate or Flowers");
        Questions.add("What's a new hobby you'd like to try?");
        Questions.add("If you could change one thing about your looks what would it be?");
        Questions.add("What's an embarrassing fashion moment?");
        Questions.add("Would you rather give up music or TV for a month?");
        Questions.add("If you had one day left to live what would you do?");
        Questions.add("What's your deepest fear?");
        Questions.add("What's your sign?");
        Questions.add("How many siblings do you have?");
        Questions.add("What's your favorite show and tell?");
        Questions.add("What's your favorite podcast?");
        Questions.add("Coffee or tea?");
        Questions.add("What's your favorite concert?");
        Questions.add("How often do you talk to your parents?");
        Questions.add("What's your favorite silly game to play? Let's play it");
        Questions.add("Favorite drink?");
        Questions.add("What's your humor like? Give me a favorite joke");
        Questions.add("Favorite hobby?");
        Questions.add("What song can always make you dance? Play it");
        Questions.add("What would your super power be?");
        Questions.add("How would you spend a million dollars?");
        Questions.add("What's your favorite song? Play it");
        Questions.add("What's your dream vacation?");
        Questions.add("Favorite childhood memory?");
        Questions.add("What are you trying to work on to better yourself?");
        Questions.add("Who's your celebrity crush?");
        Questions.add("Craziest dream?");
        Questions.add("What are your 5 and 10 year goals?");
        Questions.add("If you could live anywhere for a year where would it be?");
        Questions.add("Weirdest habit or quirk?");
        Questions.add("What's something you've always wanted to try?");
        Questions.add("What did you want to be when you grew up?");
        Questions.add("Ask me anything");
        Questions.add("Tell a crazy thing you've done");
        Questions.add("What's your favorite(or least) nickname?");
        Questions.add("If money didn't matter what would you do for a living?");
        Questions.add("Have you ever met a celebrity?");
        Questions.add("If you could meet someone famous who would it be?");
        Questions.add("Name 3 things on your bucket list");
        Questions.add("Do you have any hidden talents? Do it!!");
        Questions.add("What's the dumbest thing you've ever done?");
        Questions.add("What keeps you up at night?");
        Questions.add("What were you like in high school?");
        Questions.add("What are your 3 favorite things in the whole wide world?");
        Questions.add("What's your most enjoyable and hated household chore?");
        Questions.add("What's a guilty pleasure?");
        Questions.add("What's your favorite item of clothing?");
        Questions.add("If you had to stay home for a month what 2 things would you absolutely have to have?");
        Questions.add("What TV series have you repeatedly watched?");
        Questions.add("How have you grown or changed in the last 2 years?");
        Questions.add("What's your ideal holiday?");
        Questions.add("What was the funniest moment of your life?");
        Questions.add("What are you most proud of?");
        Questions.add("What book have you recommended the most?");
        Questions.add("What do you want your life legacy to be?");
        Questions.add("What's one small thing that always makes you smile?");
        Questions.add("If you could get rid of one habit and make a new habit what would it be?");
        Questions.add("What book, show or TV show had the biggest impact on your life?");
        Questions.add("What's your favorite flavor?");
        Questions.add("What does spending time in nature look like?");
        Questions.add("Do you prefer home cooked meals or a night out to order food? Or maybe carry out? Picnic?");
        Questions.add("If you see a butterfly what do you do?");
        Questions.add("What do you wear when you sleep?");
        Questions.add("What temperature do you sleep at?");
        Questions.add("Do you eat eggs?");
        Questions.add("What is your favorite season?");
        Questions.add("Do you ever write handwritten letters? If so to whom? If not who would you do it to?");
        Questions.add("What's your favorite museum? Which one is on your bucket list?");
        Questions.add("What's your favorite sport to play?");
        Questions.add("What's your favorite road trip? Where's your next road trip?");
        Questions.add("What's your most prized possession?");
        Questions.add("What's next on your wish list?");
        Questions.add("If you started a business what would you sell?");
        Questions.add("Whats the next movie you want to see?");
        Questions.add("What person from history would you like to meet?");
        Questions.add("What's your favorite board game?");
        Questions.add("What's your favorite city you've visited?");
        Questions.add("What fictional place do you want to visit?");
        Questions.add("What's your favorite junk food?");
        Questions.add("If you could wake up tomorrow having gained any one quality or ability, what would it be?");
        Questions.add("What junk food has no effect on you?");
        Questions.add("What would you do during a significant natural disaster (like a fire sail)?");
        Questions.add("What's your weapon of choice during a zombie apocalypse?");
        Questions.add("What's something super popular that you're not into?");
        Questions.add("What's your biggest pet peeve?");
        Questions.add("What is your most treasured memory?");
        Questions.add("What is your most terrible memory?");
        Questions.add("What are you most grateful for in life?");
        Questions.add("What are you like when there's a ton of traffic?");
        Questions.add("What is our biggest inconvenience because other people ruined it?");
        Questions.add("If you could ask anyone a question and get a legitimate answer what and who would you ask?");
    }
}
